version: 2
enable-beta-ecosystems: true
updates:
  # Github actions ecosystem.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Pub ecosystem.
  - package-ecosystem: "pub"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
