name: forge2d_workshop_presentation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  checked_yaml: ^2.0.3
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.6.0
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  super_text_layout: ^0.1.9
  syntax_highlight: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/md/
   - assets/step_02/
   - assets/step_02/bin/
   - assets/step_02/lib/
   - assets/step_03/
   - assets/step_03/assets/
   - assets/step_03/assets/images/
   - assets/step_03/bin/
   - assets/step_03/lib/
   - assets/step_03/lib/components/
   - assets/step_04/
   - assets/step_04/assets/
   - assets/step_04/assets/images/
   - assets/step_04/bin/
   - assets/step_04/lib/
   - assets/step_04/lib/components/
   - assets/step_05/
   - assets/step_05/assets/
   - assets/step_05/assets/images/
   - assets/step_05/bin/
   - assets/step_05/lib/
   - assets/step_05/lib/components/
   - assets/step_06/
   - assets/step_06/assets/
   - assets/step_06/assets/images/
   - assets/step_06/bin/
   - assets/step_06/lib/
   - assets/step_06/lib/components/
   - assets/step_07/
   - assets/step_07/assets/
   - assets/step_07/assets/images/
   - assets/step_07/bin/
   - assets/step_07/lib/
   - assets/step_07/lib/components/
