name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta      
      - run: flutter pub get
      - name: Lint analysis
        run: dart analyze
      - name: Dart format
        run: dart format --set-exit-if-changed
      - name: dart fix
        run: dart fix --dry-run
      - name: Run tests
        run: flutter test